include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.2

LUCI_TITLE:=LuCI Support for nikki-rs
LUCI_DEPENDS:=+luci-base +nikki-rs

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature